name: "DockerHubTestApp"
description: "My First Blazor App on HA"
version: "1.0.0"
slug: "docker_hub_test_app"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5333/tcp: 5333